import { Rect, Size } from "../../core/math";
import { SpriteFrame } from "../../2d/assets/sprite-frame";
import { Texture2D } from "../../asset/assets/texture-2d";
import { ImageAsset } from "../../asset/assets/image-asset";

/**
 * Create a safe 2x2 white SpriteFrame from raw pixel data.
 *
 * - Does not depend on builtinResMgr or any internal/private API.
 * - Self-contained: creates the white Texture2D from an in-memory canvas.
 * - Always has packable = false (prevents DynamicAtlas errors).
 * - Every call returns a new instance; use as a placeholder / fallback sprite.
 *
 * The engine's builtinResMgr.init() also creates its white texture from
 * the same approach (Uint8Array pixel data → ImageAsset → Texture2D).
 * So there is no duplicate resource — this is just an independent helper
 * that does not require engine subsystem initialisation.
 */
export function whiteSpriteFrame(): SpriteFrame {
    // Create 2x2 white pixel data using a temporary canvas.
    // Matches the same data generated by BuiltinResMgr.prototype.init()
    // without depending on cclegacy.builtinResMgr.
    const canvas = document.createElement("canvas");
    canvas.width = 2;
    canvas.height = 2;
    const ctx = canvas.getContext("2d")!;
    ctx.fillStyle = "#ffffff";
    ctx.fillRect(0, 0, 2, 2);

    const imageAsset = new ImageAsset(canvas);
    const tex = new Texture2D();
    tex.image = imageAsset;

    const sf = new SpriteFrame();
    sf.texture = tex;
    sf.rect = new Rect(0, 0, 2, 2);
    sf.originalSize = new Size(2, 2);
    sf.packable = false;
    return sf;
}
