import { definePlatformConfig } from '../base';
import { resolve } from 'path';

const engineRoot = resolve(__dirname, '../../..');

export default definePlatformConfig({
  name: 'native',
  
  required: {
    constants: {
      HTML5: false,
      NATIVE: true,
      JSB: true,
      ANDROID: false,
      IOS: false,
      MAC: false,
      WINDOWS: false,
      LINUX: false,
      OHOS: false,
      OPEN_HARMONY: false,
      WECHAT: false,
      WECHAT_MINI_PROGRAM: false,
      XIAOMI: false,
      ALIPAY: false,
      TAOBAO: false,
      TAOBAO_MINIGAME: false,
      BYTEDANCE: false,
      OPPO: false,
      VIVO: false,
      HUAWEI: false,
      MIGU: false,
      HONOR: false,
      COCOS_RUNTIME: false,
      EDITOR: false,
      EDITOR_NOT_IN_PREVIEW: false,
      PREVIEW: false,
      BUILD: true,
      TEST: false,
      DEBUG: false,
      DEV: false,
      SERVER_MODE: false,
      MINIGAME: false,
      RUNTIME_BASED: false,
      SUPPORT_JIT: true,
      NET_MODE: 0,
      WEBGPU: false,
      NATIVE_CODE_BUNDLE_MODE: 2,
      WASM_SUBPACKAGE: false,
      CULL_MESHOPT: true,
      LOAD_SPINE_MANUALLY: false,
      LOAD_BOX2D_MANUALLY: false,
      USE_3D: true,
      USE_UI_SKEW: false,
      USE_SORTING_2D: false,
    },
    alias: {
      'pal/audio': resolve(engineRoot, 'pal/audio/native/player.ts'),
      'pal/env': resolve(engineRoot, 'pal/env/native/env.ts'),
      'pal/system-info': resolve(engineRoot, 'pal/system-info/native/system-info.ts'),
      'pal/screen-adapter': resolve(engineRoot, 'pal/screen-adapter/native/screen-adapter.ts'),
      'pal/input': resolve(engineRoot, 'pal/input/native/index.ts'),
      'pal/pacer': resolve(engineRoot, 'pal/pacer/pacer-native.ts'),
      'pal/wasm': resolve(engineRoot, 'pal/wasm/wasm-native.ts'),
      'pal/minigame': resolve(engineRoot, 'pal/minigame/non-minigame.ts'),
    },
    output: {
      format: 'cjs',
      preserveModules: false,
    },
  },
  
  defaults: {
    features: {
      marionette: true,
    },
    build: {
      sourceMap: true,
      minify: false,
    },
  },
  
  jsbReplacements: {
    'cocos/rendering/index.ts': 'cocos/rendering/index.jsb.ts',
    'cocos/rendering/render-pipeline.ts': 'cocos/rendering/render-pipeline.jsb.ts',
    'cocos/rendering/render-stage.ts': 'cocos/rendering/render-stage.jsb.ts',
    'cocos/rendering/geometry-renderer.ts': 'cocos/rendering/geometry-renderer.jsb.ts',
    'cocos/rendering/legacy/index.ts': 'cocos/rendering/legacy/index.jsb.ts',
    'cocos/render-scene/core/native-pools.ts': 'cocos/render-scene/core/native-pools.jsb.ts',
    'cocos/render-scene/core/material-instance.ts': 'cocos/render-scene/core/material-instance.jsb.ts',
    'cocos/render-scene/core/pass.ts': 'cocos/render-scene/core/pass.jsb.ts',
    'cocos/render-scene/core/program-lib.ts': 'cocos/render-scene/core/program-lib.jsb.ts',
    'cocos/render-scene/core/render-window.ts': 'cocos/render-scene/core/render-window.jsb.ts',
    'cocos/render-scene/scene/camera.ts': 'cocos/render-scene/scene/camera.jsb.ts',
    'cocos/render-scene/scene/model.ts': 'cocos/render-scene/scene/model.jsb.ts',
    'cocos/render-scene/core/render-scene.ts': 'cocos/render-scene/core/render-scene.jsb.ts',
    'cocos/render-scene/scene/submodel.ts': 'cocos/render-scene/scene/submodel.jsb.ts',
    'cocos/render-scene/scene/index.ts': 'cocos/render-scene/scene/index.jsb.ts',
    'cocos/render-scene/scene/reflection-probe.ts': 'cocos/render-scene/scene/reflection-probe.jsb.ts',
    'cocos/2d/renderer/native-2d.ts': 'cocos/2d/renderer/native-2d.jsb.ts',
    'cocos/gfx/base/pipeline-state.ts': 'cocos/gfx/base/pipeline-state.jsb.ts',
    'cocos/gfx/base/pipeline-sub-state.ts': 'cocos/gfx/base/pipeline-sub-state.jsb.ts',
    'cocos/gfx/index.ts': 'cocos/gfx/index.jsb.ts',
    'cocos/spine/index.ts': 'cocos/spine/index.jsb.ts',
    'cocos/dragon-bones/index.ts': 'cocos/dragon-bones/index.jsb.ts',
    'cocos/scene-graph/node.ts': 'cocos/scene-graph/node.jsb.ts',
    'cocos/scene-graph/scene.ts': 'cocos/scene-graph/scene.jsb.ts',
    'cocos/scene-graph/scene-globals.ts': 'cocos/scene-graph/scene-globals.jsb.ts',
    'cocos/scene-graph/index.ts': 'cocos/scene-graph/index.jsb.ts',
    'cocos/root.ts': 'cocos/root.jsb.ts',
    'cocos/asset/asset-manager/builtin-res-mgr.ts': 'cocos/asset/asset-manager/builtin-res-mgr.jsb.ts',
    'cocos/asset/assets/index.ts': 'cocos/asset/assets/index.jsb.ts',
    'cocos/asset/assets/asset.ts': 'cocos/asset/assets/asset.jsb.ts',
    'cocos/asset/assets/buffer-asset.ts': 'cocos/asset/assets/buffer-asset.jsb.ts',
    'cocos/asset/assets/render-texture.ts': 'cocos/asset/assets/render-texture.jsb.ts',
    'cocos/asset/assets/simple-texture.ts': 'cocos/asset/assets/simple-texture.jsb.ts',
    'cocos/asset/assets/scene-asset.ts': 'cocos/asset/assets/scene-asset.jsb.ts',
    'cocos/asset/assets/effect-asset.ts': 'cocos/asset/assets/effect-asset.jsb.ts',
    'cocos/asset/assets/image-asset.ts': 'cocos/asset/assets/image-asset.jsb.ts',
    'cocos/asset/assets/texture-base.ts': 'cocos/asset/assets/texture-base.jsb.ts',
    'cocos/asset/assets/texture-2d.ts': 'cocos/asset/assets/texture-2d.jsb.ts',
    'cocos/asset/assets/texture-cube.ts': 'cocos/asset/assets/texture-cube.jsb.ts',
    'cocos/asset/assets/material.ts': 'cocos/asset/assets/material.jsb.ts',
    'cocos/asset/assets/rendering-sub-mesh.ts': 'cocos/asset/assets/rendering-sub-mesh.jsb.ts',
    'cocos/3d/assets/mesh.ts': 'cocos/3d/assets/mesh.jsb.ts',
    'cocos/3d/assets/skeleton.ts': 'cocos/3d/assets/skeleton.jsb.ts',
    'cocos/3d/models/morph-model.ts': 'cocos/3d/models/morph-model.jsb.ts',
    'cocos/3d/models/skinning-model.ts': 'cocos/3d/models/skinning-model.jsb.ts',
    'cocos/3d/models/baked-skinning-model.ts': 'cocos/3d/models/baked-skinning-model.jsb.ts',
    'cocos/3d/misc/create-mesh.ts': 'cocos/3d/misc/create-mesh.jsb.ts',
    'cocos/gi/light-probe/light-probe.ts': 'cocos/gi/light-probe/light-probe.jsb.ts',
    'cocos/gi/light-probe/delaunay.ts': 'cocos/gi/light-probe/delaunay.jsb.ts',
  },
});
